"""Initial Migration

Revision ID: 1352bdbd8192
Revises: 50fd43c7a2bd
Create Date: 2019-10-01 16:15:17.740367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1352bdbd8192'
down_revision = '50fd43c7a2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('fullname', sa.String(), nullable=True))
    op.drop_column('donations', 'fullnames')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('fullnames', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('donations', 'fullname')
    # ### end Alembic commands ###
