"""Initial Migration

Revision ID: 15724fa6ac3c
Revises: 89767f223234
Create Date: 2019-10-02 20:13:16.366620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15724fa6ac3c'
down_revision = '89767f223234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_description'), 'events', ['description'], unique=False)
    op.add_column('comments', sa.Column('event_id', sa.Integer(), nullable=False))
    op.drop_constraint('comments_donation_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'events', ['event_id'], ['id'])
    op.drop_column('comments', 'donation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('donation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_donation_id_fkey', 'comments', 'donations', ['donation_id'], ['id'])
    op.drop_column('comments', 'event_id')
    op.drop_index(op.f('ix_events_description'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
