"""Initial Migration

Revision ID: 22071ee31ff3
Revises: 15724fa6ac3c
Create Date: 2019-10-03 11:29:18.167474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22071ee31ff3'
down_revision = '15724fa6ac3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('event_id', sa.Integer(), nullable=False))
    op.drop_constraint('upvotes_donation_id_fkey', 'upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'upvotes', 'events', ['event_id'], ['id'])
    op.drop_column('upvotes', 'donation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('donation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.create_foreign_key('upvotes_donation_id_fkey', 'upvotes', 'donations', ['donation_id'], ['id'])
    op.drop_column('upvotes', 'event_id')
    # ### end Alembic commands ###
