"""Initial Migration

Revision ID: e8aafd410ab3
Revises: edb23befb9f7
Create Date: 2019-10-02 14:49:59.648942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8aafd410ab3'
down_revision = 'edb23befb9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
